<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "formation_movie"
 *
 * Auto generated by Extension Builder 2016-09-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Formation Movie',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Vincent Mariani',
	'author_email' => 'vincent.mariani@smile',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);